import type { Product, Category } from "@/lib/types"

export const products: Product[] = [
  {
    id: "prod-1",
    name: "Serene Lounge Chair",
    description:
      "A modern lounge chair with clean lines and exceptional comfort. Perfect for reading nooks or living room corners.",
    price: 599.99,
    images: [
      "/images/products/lounge-chair-1.jpg",
      "/images/products/lounge-chair-2.jpg",
      "/images/products/lounge-chair-3.jpg",
    ],
    category: "chairs",
    tags: ["furniture", "living room", "comfort"],
    rating: 4.8,
    reviews: 124,
    stock: 15,
    featured: true,
    sustainabilityScore: 4,
    colors: ["Natural Oak", "Walnut", "Black"],
    materials: ["Solid Oak", "Premium Fabric"],
  },
  {
    id: "prod-2",
    name: "Harmony Dining Table",
    description:
      "An elegant dining table that combines traditional craftsmanship with modern design. Seats up to 6 people comfortably.",
    price: 1299.99,
    images: [
      "/images/products/dining-table-1.jpg",
      "/images/products/dining-table-2.jpg",
      "/images/products/dining-table-3.jpg",
    ],
    category: "tables",
    tags: ["furniture", "dining room", "wood"],
    rating: 4.9,
    reviews: 87,
    stock: 8,
    featured: true,
    sustainabilityScore: 5,
    colors: ["Natural Oak", "Walnut"],
    materials: ["Solid Wood", "Steel"],
  },
  {
    id: "prod-3",
    name: "Tranquil Bed Frame",
    description:
      "A minimalist bed frame that creates a peaceful sleeping environment. Features a sturdy construction and elegant design.",
    price: 899.99,
    images: [
      "/images/products/bed-frame-1.jpg",
      "/images/products/bed-frame-2.jpg",
      "/images/products/bed-frame-3.jpg",
    ],
    category: "bedroom",
    tags: ["furniture", "bedroom", "sleep"],
    rating: 4.7,
    reviews: 56,
    stock: 12,
    new: true,
    sustainabilityScore: 4,
    colors: ["Oak", "Walnut", "White"],
    sizes: ["Queen", "King"],
    materials: ["Solid Wood", "Metal"],
  },
  {
    id: "prod-4",
    name: "Luminous Pendant Light",
    description:
      "A striking pendant light that adds warmth and character to any space. Features adjustable height and warm lighting.",
    price: 249.99,
    images: [
      "/images/products/pendant-light-1.jpg",
      "/images/products/pendant-light-2.jpg",
      "/images/products/pendant-light-3.jpg",
    ],
    category: "lighting",
    tags: ["lighting", "ceiling", "decor"],
    rating: 4.6,
    reviews: 42,
    stock: 20,
    featured: true,
    sustainabilityScore: 3,
    colors: ["Brass", "Black", "Copper"],
    materials: ["Metal", "Glass"],
  },
  {
    id: "prod-5",
    name: "Plush Area Rug",
    description:
      "A soft, luxurious area rug that adds texture and warmth to your floors. Made from premium materials for durability.",
    price: 349.99,
    images: [
      "/images/products/area-rug-1.jpg",
      "/images/products/area-rug-2.jpg",
      "/images/products/area-rug-3.jpg",
    ],
    category: "decor",
    tags: ["decor", "floor", "textile"],
    rating: 4.5,
    reviews: 38,
    stock: 25,
    sale: true,
    discount: 15,
    sustainabilityScore: 4,
    colors: ["Ivory", "Gray", "Navy"],
    sizes: ["5x7", "8x10", "9x12"],
    materials: ["Wool", "Cotton"],
  },
  {
    id: "prod-6",
    name: "Artisan Ceramic Vase",
    description:
      "A handcrafted ceramic vase with unique textures and glazes. Each piece is one-of-a-kind and adds artistic flair to any space.",
    price: 129.99,
    images: [
      "/images/products/ceramic-vase-1.jpg",
      "/images/products/ceramic-vase-2.jpg",
      "/images/products/ceramic-vase-3.jpg",
    ],
    category: "decor",
    tags: ["decor", "ceramic", "handmade"],
    rating: 4.9,
    reviews: 65,
    stock: 18,
    new: true,
    sustainabilityScore: 5,
    colors: ["White", "Blue", "Earth"],
    materials: ["Ceramic"],
  },
  {
    id: "prod-7",
    name: "Modular Bookshelf",
    description:
      "A customizable bookshelf system that adapts to your space and storage needs. Combine multiple units for a complete wall system.",
    price: 799.99,
    images: [
      "/images/products/bookshelf-1.jpg",
      "/images/products/bookshelf-2.jpg",
      "/images/products/bookshelf-3.jpg",
    ],
    category: "storage",
    tags: ["furniture", "storage", "living room"],
    rating: 4.7,
    reviews: 49,
    stock: 10,
    featured: true,
    sustainabilityScore: 4,
    colors: ["White", "Oak", "Black"],
    materials: ["Engineered Wood", "Steel"],
  },
  {
    id: "prod-8",
    name: "Cozy Throw Blanket",
    description:
      "A soft, luxurious throw blanket perfect for cool evenings. Made from sustainable materials with beautiful textures.",
    price: 89.99,
    images: [
      "/images/products/throw-blanket-1.jpg",
      "/images/products/throw-blanket-2.jpg",
      "/images/products/throw-blanket-3.jpg",
    ],
    category: "textiles",
    tags: ["decor", "textile", "comfort"],
    rating: 4.8,
    reviews: 112,
    stock: 35,
    sale: true,
    discount: 20,
    sustainabilityScore: 5,
    colors: ["Cream", "Gray", "Sage"],
    materials: ["Organic Cotton", "Recycled Polyester"],
  },
]

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "Living Room",
    description: "Furniture and decor for your living space",
    image: "/images/categories/living-room.jpg",
    slug: "living-room",
    featured: true,
  },
  {
    id: "cat-2",
    name: "Dining",
    description: "Tables, chairs and accessories for dining areas",
    image: "/images/categories/dining.jpg",
    slug: "dining",
    featured: true,
  },
  {
    id: "cat-3",
    name: "Bedroom",
    description: "Create your perfect sleep sanctuary",
    image: "/images/categories/bedroom.jpg",
    slug: "bedroom",
    featured: true,
  },
  {
    id: "cat-4",
    name: "Lighting",
    description: "Illuminate your space with style",
    image: "/images/categories/lighting.jpg",
    slug: "lighting",
    featured: true,
  },
  {
    id: "cat-5",
    name: "Decor",
    description: "The finishing touches for any room",
    image: "/images/categories/decor.jpg",
    slug: "decor",
    featured: true,
  },
  {
    id: "cat-6",
    name: "Outdoor",
    description: "Extend your living space to the outdoors",
    image: "/images/categories/outdoor.jpg",
    slug: "outdoor",
  },
]

export const featuredCollections = [
  {
    id: "col-1",
    name: "Scandinavian Minimalism",
    description: "Clean lines, functional design, and natural materials",
    image: "/images/rooms/modern-living-room.jpg",
    slug: "scandinavian-minimalism",
  },
  {
    id: "col-2",
    name: "Mid-Century Modern",
    description: "Iconic designs from the mid-20th century",
    image: "/images/rooms/minimalist-dining.jpg",
    slug: "mid-century-modern",
  },
  {
    id: "col-3",
    name: "Sustainable Living",
    description: "Eco-friendly materials and ethical production",
    image: "/images/rooms/A high-quality image of a modern living room setup.jpg",
    slug: "sustainable-living",
  },
]
